- label: 'Group by'
  slug: 'group_by_tag_description'
  description: 'Description of the Tag that is used for device grouping'
  value: 'Element'
- label: 'Device options'
  slug: 'device_options'
  description: 'Additional options passed to the Device constructors'
  value:
    - label: 'Device'
      description: 'Generic device without any methods'
      value: []
    - label: 'Ping'
      slug: 'ICMPable'
      description: 'Device whose state is defined by periodic ping (ICMP)'
      value:
        - label: 'Ping interval (seconds)'
          description: ''
          slug: 'ping_interval'
          type: number
          value: 30
          default: 30
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many failed pings lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
    - label: 'Wake-on-LAN'
      slug: 'WOLable'
      description: 'Device that supports Wake-on-LAN and whose state is defined by periodic ping (ICMP)'
      value:
        - label: 'Ping interval (seconds)'
          description: ''
          slug: 'ping_interval'
          type: number
          value: 30
          default: 30
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many failed pings lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
        - label: 'Wake interval (seconds)'
          description: 'Try wake every N seconds'
          slug: 'wake_interval'
          type: number
          value: 60
          default: 60
        - label: 'Max time to wake (seconds)'
          description: 'Stop trying to wake after N seconds'
          slug: 'max_time_to_wake'
          type: number
          value: 900
          default: 900
    - label: 'Avorus Probe'
      slug: 'Computer'
      description: 'Device running an Avorus-probe instance'
      value:
        - label: 'Device timeout (seconds)'
          description: 'Consider the device to be offline if no message was received after N seconds'
          slug: 'ping_max_interval'
          type: number
          value: 30
          default: 30
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many offline signals lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
        - label: 'Device interval (seconds)'
          description: 'Seconds between checking whether a "ping" message has been received'
          slug: 'ping_interval'
          type: number
          value: 5
          default: 5
        - label: 'Wake interval (seconds)'
          description: 'Try wake every N seconds'
          slug: 'wake_interval'
          type: number
          value: 60
          default: 60
        - label: 'Max time to wake (seconds)'
          description: 'Stop trying to wake after N seconds'
          slug: 'max_time_to_wake'
          type: number
          value: 900
          default: 900
        - label: 'Shutdown interval (seconds)'
          description: 'Try shutdown every N seconds'
          slug: 'shutdown_interval'
          type: number
          value: 30
          default: 30
        - label: 'Max time to shutdown (seconds)'
          description: 'Stop trying to shutdown after N seconds'
          slug: 'max_time_to_shutdown'
          type: number
          value: 900
          default: 900
        - label: 'Reboot interval (seconds)'
          description: 'Try reboot every N seconds'
          slug: 'reboot_interval'
          type: number
          value: 30
          default: 30
        - label: 'Max time to reboot (seconds)'
          description: 'Stop trying to reboot after N seconds'
          slug: 'max_time_to_reboot'
          type: number
          value: 900
          default: 900
    - label: 'PJLink'
      slug: 'PJLink'
      description: 'Monitor or Projector that supports the PJLink protocol'
      value:
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many failed pings lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
        - label: 'Watch interval (seconds)'
          description: 'Seconds between status checks'
          slug: 'watch_interval'
          type: number
          value: 10
          default: 10
        - label: 'Wake interval (seconds)'
          description: 'Try wake every N seconds'
          slug: 'wake_interval'
          type: number
          value: 30
          default: 30
        - label: 'Max time to wake (seconds)'
          description: 'Stop trying to wake after N seconds'
          slug: 'max_time_to_wake'
          type: number
          value: 900
          default: 900
        - label: 'Shutdown interval (seconds)'
          description: 'Try shutdown every N seconds'
          slug: 'shutdown_interval'
          type: number
          value: 30
          default: 30
        - label: 'Max time to shutdown (seconds)'
          description: 'Stop trying to shutdown after N seconds'
          slug: 'max_time_to_shutdown'
          type: number
          value: 900
          default: 900
        - label: 'Connection timeout (seconds)'
          description: 'TCP socket timeout'
          slug: 'connection_timeout'
          type: number
          value: 900
          default: 900
    - label: 'Gude EPC PDU'
      slug: 'GudePDU'
      description: 'GUDE Systems PDU'
      value:
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many failed pings lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
        - label: 'Watch interval (seconds)'
          description: 'Seconds between status checks'
          slug: 'watch_interval'
          type: number
          value: 10
          default: 10
        - label: 'SNMP timeout (seconds)'
          description: 'Timeout for one SNMP request/response'
          slug: 'snmp_timeout'
          type: number
          value: 5
          default: 5
        - label: 'SNMP retries'
          description: 'Number of retries to attempt in one interval'
          slug: 'snmp_retries'
          type: number
          value: 2
          default: 2
        - label: 'Write timeout (seconds)'
          description: 'Stop trying to write powerfeeds after N seconds'
          slug: 'write_powerfeeds_timeout'
          type: number
          value: 900
          default: 900
    - label: 'BrightSign®️'
      slug: 'BrightSign'
      description: 'BrightSign Digital Signage Player'
      value:
        - label: 'Offline threshold'
          slug: 'offline_count_threshold'
          description: 'How many failed pings lead to a Device being defined as "off"'
          type: number
          value: 3
          default: 3
    - label: 'LGWebOSTV'
      slug: 'LGWebOSTV'
      description: ''
      value: []
- label: 'Device mapping'
  slug: 'device_map'
  description: 'Rules that determine how to communicate with devices'
  value:
    BrightSign: []
    Computer: []
    Device: []
    GudePDU: []
    ICMPable: []
    LGWebOSTV: []
    PJLink: []
    WOLable: []
